services:
  comfyui-r9700:
    image: dorobu/comfyui-r9700:latest
    container_name: comfyui-r9700
    dns:
      - 8.8.8.8
      - 8.8.4.4
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    ipc: host
    ports:
      - "8188:8188"
    volumes:
      - ./models:/workspace/ComfyUI/models
      - ./output:/workspace/ComfyUI/output
      - ./input:/workspace/ComfyUI/input
      - ./custom_nodes:/workspace/ComfyUI/custom_nodes
      - ./user:/workspace/ComfyUI/user
      - ./miopen:/workspace/.miopen
    environment:
      - CLI_ARGS=          # e.g. --lowvram --disable-pinned-memory
    restart: unless-stopped
